# Generated by Django 5.1.6 on 2025-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_count', models.IntegerField()),
                ('done_count', models.IntegerField()),
                ('urgent_count', models.IntegerField()),
                ('most_urgent_due_date', models.DateField()),
                ('total_tasks', models.IntegerField()),
                ('in_progress_count', models.IntegerField()),
                ('awaiting_feedback_count', models.IntegerField()),
            ],
        ),
    ]
