# Generated by Django 5.1.6 on 2025-02-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0002_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task_management_app.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, to='task_management_app.subtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks_done',
            field=models.ManyToManyField(blank=True, to='task_management_app.subtaskdone'),
        ),
    ]
