# Generated by Django 5.1.6 on 2025-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0003_alter_task_assigned_users_alter_task_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='to_do', max_length=255),
        ),
    ]
