# Generated by Django 5.1.6 on 2025-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0004_delete_summary_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactNumber',
            field=models.CharField(max_length=30),
        ),
    ]
