# Generated by Django 5.1.6 on 2025-02-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0006_remove_task_subtasks_remove_task_subtasks_done_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedUser',
        ),
        migrations.DeleteModel(
            name='SubtaskDone',
        ),
    ]
