# Generated by Django 5.1.6 on 2025-02-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0007_delete_assigneduser_delete_subtaskdone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='checkbox_img',
        ),
    ]
