# Generated by Django 5.1.6 on 2025-03-08 00:32

from django.db import migrations


def add_default_categories(apps, schema_editor):
    Category = apps.get_model("task_management_app", "Category")

    initial_categories = {
        "User Story": "#0038FF",
        "Technical Task": "#1FD7C1"
    }

    for name, color in initial_categories.items():
        Category.objects.get_or_create(name=name, defaults={"color": color})


class Migration(migrations.Migration):

    dependencies = [
        ('task_management_app', '0008_remove_subtask_checkbox_img'),
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]