# Generated by Django 5.1.6 on 2025-03-08 15:35

from django.db import migrations


def add_default_priorities(apps, schema_editor):
    Prio = apps.get_model("task_management_app", "Prio")

    # predefined priorities with icons
    initial_priorities = [
        {"level": "urgent", "icon_path": "../assets/img/prio_urgent.svg"},
        {"level": "medium", "icon_path": "../assets/img/prio_medium.svg"},
        {"level": "low", "icon_path": "../assets/img/prio_low.svg"},
    ]

    for priority in initial_priorities:
        Prio.objects.get_or_create(level=priority["level"], defaults={"icon_path": priority["icon_path"]})


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_app", "0010_alter_category_color_alter_category_name"),
    ]

    operations = [
        migrations.RunPython(add_default_priorities),
    ]
