# Generated by Django 5.1.6 on 2025-03-08 16:13

from django.db import migrations


def update_priorities(apps, schema_editor):
    Prio = apps.get_model("task_management_app", "Prio")

    # Neue Struktur der initialen Prioritäten
    initial_priorities = {
        "urgent": "../assets/img/prio_urgent.svg",
        "medium": "../assets/img/prio_medium.svg",
        "low": "../assets/img/prio_low.svg",
    }

    for level, icon_path in initial_priorities.items():
        prio, created = Prio.objects.get_or_create(level=level, defaults={"icon_path": icon_path})
        
        # Falls der Eintrag existiert, aber das Icon geändert wurde, aktualisieren
        if not created and prio.icon_path != icon_path:
            prio.icon_path = icon_path
            prio.save()


class Migration(migrations.Migration):

    dependencies = [
        ("task_management_app", "0010_alter_category_color_alter_category_name"),
    ]

    operations = [
        migrations.RunPython(update_priorities),
    ]
